quiet: true

skip-check:
  - CKV_AWS_2
  - CKV_AWS_11
  - CKV_AWS_12
  - CKV_AWS_20
  - CKV_AWS_28
  - CKV_AWS_91
  - CKV_AWS_103
  - CKV_AWS_130
  - CKV_AWS_136
  - CKV_AWS_150
  - CKV_AWS_158
  - CKV_AWS_260
  - CKV_AWS_378
  - CKV_AWS_382

  - CKV2_AWS_11
  - CKV2_AWS_12
  - CKV2_AWS_20
  - CKV2_AWS_28
