name: Continuous Deployment

on:
  workflow_run:
      workflows: ["Continuous Integration"]  # Must match the 'name:' in ci.yml
      types:
        - completed
      branches: [ main ]

permissions:
  id-token: write
  contents: read

concurrency:
  group: ecs-production
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- 1. AWS AUTHENTICATION & ECR LOGIN ---
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- 2. BUILD & PUSH DOCKER IMAGE ---
      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: flask-ecs-devops-pipeline
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            --build-arg APP_VERSION=${IMAGE_TAG} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


      # --- 3. ECS DEPLOYMENT ---
      - name: Download Current Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition flask-ecs-devops-pipeline \
            --query taskDefinition | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' > task-definition.json

      - name: Render ECS Task Definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: flask-ecs-devops-pipeline
          image: ${{ steps.login-ecr.outputs.registry }}/flask-ecs-devops-pipeline:${{ github.sha }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          cluster: shaurya-devops-ecs-cluster
          service: shaurya-devops-flask-service
          wait-for-service-stability: true
