name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: terraform

        run: terraform fmt -check -recursive

      - name: Terraform Initialize
        working-directory: terraform

        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform

        run: terraform validate
