name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python Dependencies
        working-directory: app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Python Syntax Check
        working-directory: app
        run: |
          python -m compileall .

      - name: Verify Flask Imports
        working-directory: app
        run: |
          python -c "import app"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: terraform

        run: terraform fmt -check -recursive

      - name: Terraform Initialize
        working-directory: terraform

        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform

        run: terraform validate

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v12

        with:
          directory: terraform
          framework: terraform
          quiet: true

      - name: Build Docker Image
        run: |
          docker build \
            -t flask-ecs-cicd-demo:test \
            app

      - name: Start Container
        run: |
          docker run -d \
            --name flask-demo \
            -p 5000:5000 \
            flask-ecs-cicd-demo:test

      - name: Wait for Startup
        run: sleep 5

      - name: Verify Health Endpoint
        run: |
          curl --fail http://localhost:5000/health

      - name: Verify Info Endpoint
        run: |
          curl --fail http://localhost:5000/info

      - name: Cleanup
        if: always()

        run: |
          docker stop flask-demo
          docker rm flask-demo
